name = "MacroEnergy"
uuid = "260b7737-bf0e-4e84-9335-3af14438b1f5"
version = "0.0.2"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ClusterManagers = "34f1f09b-3a8b-5176-ab39-66d58a4d544e"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
DuckDB_jll = "2cbbab25-fc8b-58cf-88d4-687a02676033"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MacroEnergyScaling = "824dc6dc-8db5-4e55-923f-6cabbd6cfcd5"
MacroEnergySolvers = "466a4f75-6c9c-4ef2-97df-f5f43ac00c23"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[weakdeps]
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"

[extensions]
MacroEnergyGurobiExt = "Gurobi"

[compat]
BenchmarkTools = "1"
CSV = "0.10"
ClusterManagers = "2"
DBInterface = "2"
DataFrames = "1.7"
Dates = "1"
Distributed = "1"
DistributedArrays = "0.6"
DuckDB = "0.10"
GZip = "0.6"
GitHub = "5"
Gurobi = "1"
HiGHS = "1"
InteractiveUtils = "1"
JSON3 = "1"
JuMP = "1"
Logging = "1"
LoggingExtras = "1.1.0"
MacroEnergyScaling = "0.2"
MacroEnergySolvers = "0.1"
Markdown = "1"
OrderedCollections = "1"
Parquet2 = "0.2"
Pkg = "1"
Printf = "1"
Random = "1"
Revise = "3"
Test = "1"
YAML = "0.4"
julia = "1"

[extras]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "JLD2", "Logging", "LoggingExtras"]
